apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ include "fullName" . }}
  name: {{ include "fullName" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "fullName" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "fullName" . }}
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: APIKEY
              value: {{ .Values.apikey | quote }}
            - name: QUARKUS_DATASOURCE_USERNAME
              value: {{ .Values.db.username | quote }}
            - name: QUARKUS_DATASOURCE_PASSWORD
              value: {{ .Values.db.password | quote }}
            - name: QUARKUS_DATASOURCE_JDBC_URL
              value: {{ printf "jdbc:mysql://%s:3306/%s" .Values.db.hostname .Values.db.dbname | quote }}
          image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          name: antennas-incident
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
