apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: {{ include "fullName" . }}
  name: {{ include "fullName" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "fullName" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "fullName" . }}
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: APIKEY
              value: {{ .Values.incident.apikey | quote }}
            - name: QUARKUS_REST_CLIENT_INCIDENT_SERVICE_URL
              value: {{ .Values.incident.url | quote }}
{{- if ne .Values.image.digest "" }}
          image: {{ printf "%s@%s" .Values.image.repository .Values.image.digest | quote }}
{{- else }}
          image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag | quote }}
{{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          name: antennas-front
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 5
